language: node_js
node_js:
  - '10'
script:
  - npm run build
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: build
  on:
    branch: master
  fqdn: dev.ib.org.au
